FROM python:3.8

ENV VAR1 10

WORKDIR /dashboard

COPY requirements.txt /
RUN pip install  -r  /requirements.txt
COPY dashboard  .
RUN chmod +x wait-for-it.sh

CMD ["./wait-for-it.sh", "portfolio_manager:8000", "-t", "0", "--", "python", "./app.py"]
