version: "2"

services:
  crypto_db:
    image: postgres:12.2-alpine
    env_file: database/.env
    ports:
      - 5432:5432
    restart: "unless-stopped"
    volumes:
      - ./data:/var/lib/postgres/data
    
  portfolio_manager:
    build: ./portfolio_manager
    depends_on:
      - beverly_hills
      - main_data_consumer
    restart: "on-failure"
    env_file: portfolio_manager/.env
    ports:
      - 4000:4000
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined

  beverly_hills:
    build: ./beverly_hills
    depends_on: 
      - crypto_db
      - main_data_consumer
    restart: "on-failure"
    env_file: beverly_hills/.env

  main_data_consumer:
    build: ./main_data_consumer
    depends_on:
      - crypto_db
    restart: "on-failure"
    env_file: main_data_consumer/.env
    ports:
      - "4040:4040"
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined
  
  frontend:
    build: ./frontend
    depends_on: 
      - main_data_consumer
      - beverly_hills
      - portfolio_manager
    command: "sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 dashboard/start.py "
    restart: "on-failure"
    env_file: frontend/.env
    ports:
      - "1337:1337"
    