version: "2"

services:
  crypto_db:
    image: postgres:12.2-alpine
    env_file: database/.env
    ports:
      - 5432:5432
    restart: "unless-stopped"
    volumes:
      - ./data:/var/lib/postgres/data
    
  portfolio_manager:
    build: ./portfolio_manager
    depends_on:
      # - beverly_hills
      - main_data_consumer
    restart: "on-failure"
    env_file: portfolio_manager/.env
    ports:
      - 4000:4000
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined

  beverly_hills:
    build: ./beverly_hills
    depends_on: 
      - crypto_db
      - main_data_consumer
    restart: "on-failure"
    env_file: beverly_hills/.env
    ports:
      - 1234:1234

  main_data_consumer:
    build: ./main_data_consumer
    depends_on:
      - crypto_db
    restart: "on-failure"
    env_file: main_data_consumer/.env
    ports:
      - "4040:4040"
      - "9090:9090"
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined