version: "3"
services:
  crypto_db:
    image: postgres:12.2-alpine
    env_file: production/env/.env_db
    ports:
      - 5432:5432
    restart: "unless-stopped"
    
  golang_trade:
    build: ./production/golang
    depends_on:
      - crypto_db
      - python_trade
    restart: "on-failure"
    env_file: production/golang/env/.env_trade

  python_trade:
    build: ./production/python
    depends_on: 
      - crypto_db
    restart: "on-failure"
    ports:
      - 1234:1234
    