version: "3"
services:
  crypto_db:
    image: postgres:12.2-alpine
    env_file: production/env/.env_db
    ports:
      - 5432:5432
    restart: "unless-stopped"
    
  trade:
    build: ./production
    depends_on:
      - crypto_db
    restart: "on-failure"
    env_file: production/env/.env_trade
